#############################################
# To submit a plugin add a new entry to this file.
#############################################

# Structure:
# - name: Name of the plugin
# - tagline: Very concise description of the plugin
# - url: Link to the Git repository/website
# - logo (optional): Relative link to the logo placed in the `/static/plugins-data/logos/` directory (without the `/static/` though)
# - tags: Tags for the plugin. Capitalized
# - featured (optional): Whether the plugin is featured at the top. A maximum of 4 are shown
# - weight (optional): Determines the sort order. A higher weight comes first.

# hy3

[[plugins]]
name     = "hy3"
url      = "https://github.com/outfoxxed/hy3"
category = "Layout"
tagline  = "i3 / Sway like layout"
logo     = "/plugins-data/logos/hy3-logo.svg"
banner   = "/plugins-data/hy3_banner.mp4"
featured = true

# Quality of Life

[[plugins]]
name     = "Hyprwinwrap"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/hyprwinwrap"
category = "Quality of Life"
tagline  = "Any app as wallpaper"
logo     = "/plugins-data/logos/hyprwinwrap-logo.svg"

[[plugins]]
name     = "hyprgrass"
url      = "https://github.com/horriblename/hyprgrass"
category = "Quality of Life"
tagline  = "Touch gestures"
featured = true

[[plugins]]
name     = "split-monitor-workspaces"
url      = "https://github.com/Duckonaut/split-monitor-workspaces"
category = "Quality of Life"
tagline  = "Awesome-like workspace behavior"

[[plugins]]
name     = "hyprland-easymotion"
url      = "https://github.com/zakk4223/hyprland-easymotion"
category = "Quality of Life"
tagline  = "Easymotion, for Hyprland"

[[plugins]]
name     = "hypr-dynamic-cursors"
url      = "https://github.com/VirtCode/hypr-dynamic-cursors"
category = "Quality of Life"
tagline  = "Cursor physics for Hyprland"

[[plugins]]
name     = "xtra-dispatchers"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/xtra-dispatchers"
category = "Quality of Life"
tagline  = "Additional dispatchers for Hyprland"

[[plugins]]
name     = "hypr-kinetic-scroll"
url      = "https://github.com/savonovv/hypr-kinetic-scroll"
category = "Quality of Life"
tagline  = "Compositor-level kinetic touchpad scrolling"

# Layout

[[plugins]]
name     = "hyprNStack"
url      = "https://github.com/zakk4223/hyprNStack"
category = "Layout"
tagline  = "N-Stack tiling"

[[plugins]]
name     = "hyprland-virtual-desktops"
url      = "https://github.com/levnikmyskin/hyprland-virtual-desktops"
category = "Layout"
tagline  = "Virtual desktops"

[[plugins]]
name     = "hyprscrolling"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/hyprscrolling"
category = "Layout"
tagline  = "Scrolling layout for Hyprland"

[[plugins]]
name     = "hyprRiver"
url      = "https://github.com/zakk4223/hyprRiver"
category = "Layout"
tagline  = "River layouts, on Hyprland"

# Design

[[plugins]]
name     = "Borders++"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/borders-plus-plus"
category = "Design"
tagline  = "Extra window borders"
logo     = "/plugins-data/logos/Borders-plus-plus-logo.svg"

[[plugins]]
name     = "Image borders"
url      = "https://codeberg.org/zacoons/imgborders"
category = "Design"
tagline  = "Add tiling image borders to windows!"
logo     = "/plugins-data/logos/imgborders.svg"

[[plugins]]
name     = "Hyprbars"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/hyprbars"
category = "Design"
tagline  = "Bring back title bars"
logo     = "/plugins-data/logos/hyprbars-logo.svg"
featured = true

[[plugins]]
name     = "Hyprtrails"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/hyprtrails"
category = "Design"
tagline  = "Smooth window trails"
logo     = "/plugins-data/logos/hyprtrails-logo.svg"
featured = false

[[plugins]]
name     = "Hyprfocus"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/hyprfocus"
category = "Design"
tagline  = "Flashfocus for Hyprland"

[[plugins]]
name     = "hypr-darkwindow"
url      = "https://github.com/micha4w/Hypr-DarkWindow"
category = "Design"
tagline  = "Invert window colors"

[[plugins]]
name     = "hyprexpo"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/hyprexpo"
category = "Design"
tagline  = "Zoomed out workspace overview"
featured = true

[[plugins]]
name     = "hyprspace"
url      = "https://github.com/KZDKM/Hyprspace"
category = "Design"
tagline  = "MacOS-like workspace overview"
featured = true

# Miscellaneous

[[plugins]]
name     = "pyprland"
url      = "https://github.com/hyprland-community/pyprland"
category = "Miscellaneous"
tagline  = "Python framework for Hyprland's IPC"
featured = true

[[plugins]]
name     = "CSGO Vulkan Fix"
url      = "https://github.com/hyprwm/hyprland-plugins/tree/main/csgo-vulkan-fix"
category = "Miscellaneous"
tagline  = "CSGO custom resolutions fix"


[[plugins]]
name     = "hypr-hot-edge"
url      = "https://github.com/claychinasky/hypr-hot-edge"
category = "Miscellaneous"
tagline  = "Hot Edge Side Panel Like Workspaces"
